baseURL = "https://label.drylungs.at"
title = "Dry Lungs"
languageCode = "en-us"
defaultContentLanguage = "en"
theme_color = "#000000"
disableHugoGeneratorInject = true

[params]
	theme = "polivoks"
	description = "Dry Lungs Records &amp; Mailorder"
	images = ["drylungs-cover.png"]
    customCSS = []
    customJS  = []
    author = "christoph@drylungs.at"
    publisher = "christoph@drylungs.at"
    email = "christoph@drylungs.at"
    google_site_verification = "btMQPqnHIshsheX-njuIUKtyLqv81aeN0yEeo2c65eU"
[params.social]
    bigcartel = { user = "drylungs", uri = "https://drylungs.bigcartel.com/" }
    discogs = { user = "KureKureTakora", uri = "https://www.discogs.com/seller/KureKureTakora" }
    instagram = { user = "drylungsrecords", uri = "https://www.instagram.com/drylungsrecords" }
    twitter = "DryLungsRecords"

[author]
    email="tong@disktree.net"
    web = "https://disktree.net"

[taxonomies]
    artist = "artists"
